### ISSUE TITLE
Redundant Initialization Pattern

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#140]
## ZMT-01C: Redundant Initialization Pattern

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [ZapMarket.sol:L155-L161](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L155-L161) |

### Description:

The linked `initialize` function is ineffectual as it simply sets a flag that it solely uses to prevent repeat invocations.

### Example:

```solidity
function initialize() public override initializer {
    require(!initialized, "Market: Instance has already been initialized");

    initialized = true;

    // _owner = msg.sender;
}
```

### Recommendation:

We advise it along with the `Initializable` contract inheritence to be removed.

**Comment by Kaleb47** [comment]
We've updated the smart contract since the audit and we can't get rid of the initialize function. Please advise.

**Comment by kimanikelly** [comment]
The initializer function can not be removed due to its upgradeability depending on it. The function can be reconfigured to omit these lines.

``` 
require(!initialized, 'Market: Instance has already been initialized');
initialized = true; 
```
No need to verify if the media contract is initialized directly inside the function body due to it already being checked from the ```initializer``` inheritance.

Removal of the redundant initialized check
<img width="874" alt="Screen Shot 2021-10-04 at 12 35 31 PM" src="https://user-images.githubusercontent.com/42893948/135889743-f3e09d7b-c6b9-4546-88b5-594eff3d796f.png">


The require statement is provided by the ```initializer``` inheritance with the same output
<img width="1147" alt="Screen Shot 2021-10-04 at 12 36 36 PM" src="https://user-images.githubusercontent.com/42893948/135889876-17147582-7788-4ba7-a9a6-e4ba16736dfe.png">
