### ISSUE TITLE
Add Access Control to ZapMaster functions

### ISSUE THREAD

**Issue by taejoonn** [zapproject/hardhat-bsc#223]
### Summary
There are currently no access control for `changeDeity()`, `changeZapContract()`, and `changeVaultContract()`. These functions should be restricted to only the owner of the contract.

### Definition of Done
Tests that verifies access control to said functions.

**Comment by acemasterjb** [comment]
I started working on this today, I thought of utilising the existing `proposeFork` function, where instead of using the `isZM` boolean, it uses a `uint256` to check what needs to be forked:

0 - No Contract will be forked
1 - The Zap Contract will be forked
2 - Zap Master will be forked
3 - Vault Contract will be forked

I also noticed that the ZM funds were not being transferred once its forked, so I will add that logic to this function within Zap.sol.
