### ISSUE TITLE
Fetch Permit Nonce

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/hardhat-bsc#304]
### Description

Write and test a function to test the permit nonce.

```
public async fetchPermitNonce(
    address: string,
    mediaId: BigNumberish
  ): Promise<BigNumber> {
    return this.media.permitNonces(address, mediaId)
  }
```

### Definition of Done

The function passes the test and is merged to the current changes.

**Comment by jpkim921** [comment]
Adding fetchPermitNonce looks straightforward but to test it we also need `permit()` function added to zapMedia.

**Comment by jpkim921** [comment]
added function and test. All tests passing. but added a .skip to fetchPermitNonce and Permit tests since those need wallets to sign.

if you really want to run those tests, for now run ganache-cli with this particular mnemonic:
`ganache-cli --mnemonic "ostrich mixture embrace quote comic until exchange rubber butter royal august stay"`
