### ISSUE TITLE
 permit

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/hardhat-bsc#314]
### Descritpion

Write and test a function that approves meta transactions as outlined in [EIP-712](https://eips.ethereum.org/EIPS/eip-712#abstract)

```
 /**
   * Grants the spender approval for the specified media using meta transactions as outlined in EIP-712
   * @param sender
   * @param mediaId
   * @param sig
   */
  public async permit(
    spender: string,
    mediaId: BigNumberish,
    sig: EIP712Signature
  ): Promise<ContractTransaction> {
    try {
      this.ensureNotReadOnly()
    } catch (err) {
      return Promise.reject(err.message)
    }

    return this.media.permit(spender, mediaId, sig)
  }

```

### Definition of Done

Hash approval is successful.

**Comment by jpkim921** [comment]
added function and test. All tests passing. but added a .skip to fetchPermitNonce and Permit tests since those need wallets to sign.

if you really want to run those tests, for now run ganache-cli with this particular mnemonic:
`ganache-cli --mnemonic "ostrich mixture embrace quote comic until exchange rubber butter royal august stay"`
